//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.RewardAndRecognition {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.RewardAndRecognition.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new awards captain is....
        /// </summary>
        public static string AdminHeaderText {
            get {
                return ResourceManager.GetString("AdminHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string AdminSubheaderText {
            get {
                return ResourceManager.GetString("AdminSubheaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Workplace Awards tab to setup and manage reward cycles..
        /// </summary>
        public static string AdminTabNavigationText {
            get {
                return ResourceManager.GetString("AdminTabNavigationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already endorsed **{0}** for this award..
        /// </summary>
        public static string AlreadyEndorsedMessage {
            get {
                return ResourceManager.GetString("AlreadyEndorsedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And the winners are….
        /// </summary>
        public static string AwardWinnerCardTitle {
            get {
                return ResourceManager.GetString("AwardWinnerCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set awards captain.
        /// </summary>
        public static string ConfigureAdminTitle {
            get {
                return ResourceManager.GetString("ConfigureAdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to get started? Select your awards captain.
        /// </summary>
        public static string ContentText {
            get {
                return ResourceManager.GetString("ContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This reward cycle is closed..
        /// </summary>
        public static string CycleClosedMessage {
            get {
                return ResourceManager.GetString("CycleClosedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re not currently in an active award cycle. Wait until the next cycle to nominate or endorse a teammate..
        /// </summary>
        public static string CycleValidationMessage {
            get {
                return ResourceManager.GetString("CycleValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorse.
        /// </summary>
        public static string EndorseButtonText {
            get {
                return ResourceManager.GetString("EndorseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endorse.
        /// </summary>
        public static string EndorseTitle {
            get {
                return ResourceManager.GetString("EndorseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Try again in a few minutes..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot cannot be used here because it has not been added for this team..
        /// </summary>
        public static string InvalidTeamText {
            get {
                return ResourceManager.GetString("InvalidTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected tenant id found..
        /// </summary>
        public static string InvalidTenantText {
            get {
                return ResourceManager.GetString("InvalidTenantText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Allow nomination of your team mates for designated awards..
        /// </summary>
        public static string ManageAwardsBulletPoint {
            get {
                return ResourceManager.GetString("ManageAwardsBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app not available in 1:1 or group chats. To send an award, navigate to a team where Workplace Awards has been added..
        /// </summary>
        public static string MessagingExtensionErrorMessage {
            get {
                return ResourceManager.GetString("MessagingExtensionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Approve and publish the award winners from the list of nominees..
        /// </summary>
        public static string NominateBulletPoint {
            get {
                return ResourceManager.GetString("NominateBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominate.
        /// </summary>
        public static string NominateButton {
            get {
                return ResourceManager.GetString("NominateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominate now.
        /// </summary>
        public static string NominateButtonText {
            get {
                return ResourceManager.GetString("NominateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominated by {0}..
        /// </summary>
        public static string NominatedByText {
            get {
                return ResourceManager.GetString("NominatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominate people.
        /// </summary>
        public static string NominatePeopleTitle {
            get {
                return ResourceManager.GetString("NominatePeopleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been nominated for this award. Feel free to endorse them! Thanks so much! - {1} ..
        /// </summary>
        public static string NominationMentionText {
            get {
                return ResourceManager.GetString("NominationMentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominations are about to close, please nominate now..
        /// </summary>
        public static string NominationReminderNotificationText {
            get {
                return ResourceManager.GetString("NominationReminderNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Note from team owner:** {0}.
        /// </summary>
        public static string NoteForTeamText {
            get {
                return ResourceManager.GetString("NoteForTeamText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward cycle has been configured from **{0}**  to **{1}**..
        /// </summary>
        public static string RewardCycleHeader {
            get {
                return ResourceManager.GetString("RewardCycleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward cycle:.
        /// </summary>
        public static string RewardCycleText {
            get {
                return ResourceManager.GetString("RewardCycleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s reward time!.
        /// </summary>
        public static string RewardTitle {
            get {
                return ResourceManager.GetString("RewardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Set awards captain who can define awards and manage reward nomination cycles..
        /// </summary>
        public static string SetAdminBulletPoint {
            get {
                return ResourceManager.GetString("SetAdminBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set awards captain.
        /// </summary>
        public static string SetAdminButtonText {
            get {
                return ResourceManager.GetString("SetAdminButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As awards captain, {0} will define the awards, set the awards cycle, and share the results. Thanks so much! - {1}..
        /// </summary>
        public static string SetAdminMentionText {
            get {
                return ResourceManager.GetString("SetAdminMentionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * Show support for nominees by endorsing their nominations..
        /// </summary>
        public static string SetRewardCycleBulletPoint {
            get {
                return ResourceManager.GetString("SetRewardCycleBulletPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully endorsed the nomination of **{0}** for the **{1}**. Results will be shared on **{2}.**.
        /// </summary>
        public static string SuccessfulEndorseMessage {
            get {
                return ResourceManager.GetString("SuccessfulEndorseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I don&apos;t know that command. Try typing command:
        ///-Nominate.
        /// </summary>
        public static string UnsupportedBotCommand {
            get {
                return ResourceManager.GetString("UnsupportedBotCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **View published results on Workplace Awards tab.**.
        /// </summary>
        public static string ViewWinnerTabText {
            get {
                return ResourceManager.GetString("ViewWinnerTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **The existing awards captain has left the team. Please choose a new awards captain to proceed.**.
        /// </summary>
        public static string WelcomeCardNewAdminText {
            get {
                return ResourceManager.GetString("WelcomeCardNewAdminText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string WelcomeCardTitle {
            get {
                return ResourceManager.GetString("WelcomeCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are some of the things that I can help you do:.
        /// </summary>
        public static string WelcomeSubHeaderText {
            get {
                return ResourceManager.GetString("WelcomeSubHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, I am Workplace Awards bot and I can help you nominate your team members for performance awards..
        /// </summary>
        public static string WelcomeTeamCardContent {
            get {
                return ResourceManager.GetString("WelcomeTeamCardContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the reward cycle.
        /// </summary>
        public static string WinnerCardRewardCycleTitle {
            get {
                return ResourceManager.GetString("WinnerCardRewardCycleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations .
        /// </summary>
        public static string WinnerMentionText {
            get {
                return ResourceManager.GetString("WinnerMentionText", resourceCulture);
            }
        }
    }
}
